import {
  permissionKeys,
  type MenuDefinition,
  type Permission,
  type UserRole,
} from "./types"

const allPermissions = [...permissionKeys]
const divisionOperationsPermissions: Permission[] = [
  "dashboard.read",
  "schedules.read",
  "announcements.read",
  "committees.read",
  "tasks.read",
  "tasks.update",
  "issues.read",
  "issues.create",
  "issues.update",
  "issues.resolve",
  "handoffs.read",
  "handoffs.create",
  "handoffs.accept",
  "handoffs.block",
  "handoffs.complete",
  "venues.read",
  "event_day.read",
  "event_operations.read",
  "notifications.read",
  "notifications.update",
]

export const rolePermissions: Record<UserRole, Permission[]> = {
  super_admin: allPermissions,
  ketua_pelaksana: [
    "dashboard.read",
    "users.read",
    "competitions.read",
    "schedules.read",
    "schedules.update",
    "announcements.read",
    "announcements.approve",
    "announcements.publish",
    "publications.read",
    "media.read",
    "committees.read",
    "committees.update",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.assign",
    "issues.resolve",
    "issues.close",
    "issues.escalate",
    "handoffs.read",
    "handoffs.create",
    "handoffs.update",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "venues.update",
    "event_day.read",
    "analytics.read",
    "reports.read",
    "event_operations.read",
    "event_operations.update",
    "division_status.read",
    "audit.read",
    "notifications.read",
    "notifications.update",
    "notifications.send",
  ],
  wakil_ketua: [
    "dashboard.read",
    "users.read",
    "competitions.read",
    "schedules.read",
    "schedules.update",
    "announcements.read",
    "announcements.approve",
    "announcements.publish",
    "publications.read",
    "media.read",
    "committees.read",
    "committees.update",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.assign",
    "issues.resolve",
    "issues.close",
    "issues.escalate",
    "handoffs.read",
    "handoffs.create",
    "handoffs.update",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "venues.update",
    "event_day.read",
    "analytics.read",
    "reports.read",
    "event_operations.read",
    "event_operations.update",
    "division_status.read",
    "audit.read",
    "notifications.read",
    "notifications.update",
    "notifications.send",
  ],
  sekretaris: [
    "dashboard.read",
    "schedules.read",
    "schedules.create",
    "schedules.update",
    "announcements.read",
    "documents.read",
    "documents.update",
    "reports.read",
    "tasks.read",
    "issues.read",
    "issues.create",
    "handoffs.read",
    "venues.read",
    "event_day.read",
    "notifications.read",
    "notifications.update",
  ],
  bendahara: [
    "dashboard.read",
    "finances.read",
    "finances.update",
    "reports.read",
    "announcements.read",
    "issues.read",
    "handoffs.read",
    "venues.read",
    "event_day.read",
    "notifications.read",
    "notifications.update",
  ],
  acara: [
    ...divisionOperationsPermissions,
    "schedules.create",
    "schedules.update",
    "event_operations.update",
    "reports.read",
  ],
  pj_lomba: [
    "dashboard.read",
    "competitions.read",
    "competitions.update",
    "competitions.status.update",
    "participants.read",
    "participants.update",
    "scores.update",
    "schedules.read",
    "schedules.update",
    "announcements.read",
    "media.read",
    "committees.read",
    "tasks.read",
    "tasks.update",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.resolve",
    "handoffs.read",
    "handoffs.create",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "event_day.read",
    "notifications.read",
    "notifications.update",
  ],
  humas: [
    "dashboard.read",
    "schedules.read",
    "announcements.read",
    "announcements.create",
    "announcements.update",
    "announcements.publish",
    "publications.read",
    "publications.update",
    "media.read",
    "committees.read",
    "tasks.read",
    "tasks.update",
    "notifications.read",
    "notifications.update",
    "notifications.send",
    "issues.read",
    "issues.create",
    "issues.update",
    "handoffs.read",
    "handoffs.create",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "event_day.read",
  ],
  dokumentasi: [
    "dashboard.read",
    "schedules.read",
    "announcements.read",
    "media.read",
    "media.upload",
    "media.update",
    "publications.read",
    "committees.read",
    "tasks.read",
    "tasks.update",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.resolve",
    "handoffs.read",
    "handoffs.create",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "event_day.read",
    "notifications.read",
    "notifications.update",
  ],
  kebersihan: [
    ...divisionOperationsPermissions,
    "reports.read",
  ],
  perlengkapan: [
    ...divisionOperationsPermissions,
    "reports.read",
  ],
  keamanan: [
    ...divisionOperationsPermissions,
    "reports.read",
  ],
  kewirausahaan: [
    ...divisionOperationsPermissions,
    "publications.read",
    "reports.read",
  ],
  operator: [
    "dashboard.read",
    "competitions.read",
    "participants.read",
    "scores.update",
    "schedules.read",
    "schedules.update",
    "announcements.read",
    "media.read",
    "tasks.read",
    "tasks.update",
    "technical_operations.read",
    "technical_operations.update",
    "event_operations.read",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.resolve",
    "handoffs.read",
    "handoffs.create",
    "handoffs.accept",
    "handoffs.block",
    "handoffs.complete",
    "venues.read",
    "venues.update",
    "event_day.read",
    "notifications.read",
    "notifications.update",
  ],
}

export const menuDefinitions: MenuDefinition[] = [
  { key: "dashboard", label: "Dashboard", href: "/dashboard", requiredPermission: "dashboard.read" },
  { key: "users", label: "Users", href: "/dashboard/users", requiredPermission: "users.read" },
  { key: "competitions", label: "Competitions", href: "/dashboard/tournament", requiredPermission: "competitions.read" },
  { key: "participants", label: "Participants", href: "/dashboard/participants", requiredPermission: "participants.read" },
  { key: "schedules", label: "Schedules", href: "/dashboard/schedules", requiredPermission: "schedules.read" },
  { key: "announcements", label: "Announcements", href: "/dashboard/announcements", requiredPermission: "announcements.read" },
  { key: "publications", label: "Publications", href: "/dashboard/humas-sponsorship", requiredPermission: "publications.read" },
  { key: "media", label: "Media Center", href: "/dashboard/media", requiredPermission: "media.read" },
  { key: "documents", label: "Documents", href: "/dashboard/documents", requiredPermission: "documents.read" },
  { key: "finances", label: "Finances", href: "/dashboard/budgeting", requiredPermission: "finances.read" },
  { key: "committees", label: "Committee", href: "/dashboard/panitia-management", requiredPermission: "committees.read" },
  { key: "tasks", label: "Tasks", href: "/dashboard/tasks", requiredPermission: "tasks.read" },
  { key: "issues", label: "Kendala Aktif", href: "/dashboard/issues", requiredPermission: "issues.read" },
  { key: "handoffs", label: "Handoff Divisi", href: "/dashboard/handoffs", requiredPermission: "handoffs.read" },
  { key: "venues", label: "Status Venue", href: "/dashboard/venues", requiredPermission: "venues.read" },
  { key: "event-day", label: "Mode Hari-H", href: "/dashboard/event-day", requiredPermission: "event_day.read" },
  { key: "analytics", label: "Analytics", href: "/dashboard/analytics", requiredPermission: "analytics.read" },
  { key: "audit", label: "Audit Log", href: "/dashboard/audit", requiredPermission: "audit.read" },
  { key: "settings", label: "Settings", href: "/dashboard/settings", requiredPermission: "settings.read" },
]

export function getRolePermissions(role: UserRole) {
  return rolePermissions[role] ?? []
}

export function can(role: UserRole, permission: Permission) {
  return getRolePermissions(role).includes(permission)
}

export function getAllowedMenus(role: UserRole) {
  return menuDefinitions.map((menu) => ({
    ...menu,
    allowed: can(role, menu.requiredPermission),
  }))
}
